<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Final.CPU8086</RootNamespace>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.17" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.17" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.17" />
    <PackageReference Include="Avalonia.Xaml.Interactivity" Version="11.3.0" />
    <PackageReference Include="Avalonia.Xaml.Interactions" Version="11.3.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <!-- nur im Debug aktiv (DevTools via F12) -->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.3.17" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CPU8086.Resources\CPU8086.Resources.csproj" />
    <ProjectReference Include="..\CPU8086\CPU8086.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**\*.png" />
  </ItemGroup>

</Project>
